{
  "gold_per_floor": [
    110,
    185,
    185,
    204,
    204,
    204,
    233,
    244,
    268,
    88,
    88,
    103,
    103,
    118,
    118,
    191,
    191,
    201,
    201,
    126,
    144,
    155,
    155,
    181,
    193,
    231,
    270,
    315,
    327,
    339,
    364,
    376,
    464,
    476,
    508,
    188,
    188,
    11,
    233,
    233,
    262,
    21,
    68,
    94,
    108,
    118,
    118,
    118,
    118,
    118,
    118,
    118,
    118,
    27,
    60,
    60
  ],
  "floor_reached": 57,
  "playtime": 5403,
  "items_purged": [
    "Strike_B",
    "Barrage"
  ],
  "score": 2913,
  "play_id": "8e0492a7-0527-43f1-a0dd-cf225c6c6394",
  "local_time": "20190303133428",
  "is_ascension_mode": true,
  "campfire_choices": [
    {
      "floor": 6,
      "key": "REST"
    },
    {
      "data": "Zap",
      "floor": 11,
      "key": "SMITH"
    },
    {
      "data": "Coolheaded",
      "floor": 13,
      "key": "SMITH"
    },
    {
      "data": "Hologram",
      "floor": 15,
      "key": "SMITH"
    },
    {
      "data": "Fusion",
      "floor": 23,
      "key": "SMITH"
    },
    {
      "floor": 25,
      "key": "REST"
    },
    {
      "data": "Biased Cognition",
      "floor": 30,
      "key": "SMITH"
    },
    {
      "floor": 32,
      "key": "REST"
    },
    {
      "data": "Fission",
      "floor": 40,
      "key": "SMITH"
    },
    {
      "data": "Seek",
      "floor": 47,
      "key": "SMITH"
    },
    {
      "floor": 49,
      "key": "RECALL"
    },
    {
      "data": "Loop",
      "floor": 53,
      "key": "SMITH"
    }
  ],
  "neow_cost": "NONE",
  "seed_source_timestamp": 0,
  "circlet_count": 0,
  "master_deck": [
    "AscendersBane",
    "Zap+1",
    "Compile Driver",
    "Coolheaded+1",
    "Conserve Battery",
    "Gash",
    "Fusion+1",
    "Hologram+1",
    "Core Surge",
    "Seek+1",
    "Amplify",
    "Force Field",
    "Auto Shields",
    "Steam+1",
    "White Noise+1",
    "Coolheaded",
    "Compile Driver",
    "Biased Cognition+1",
    "Compile Driver",
    "BootSequence",
    "Fission+1",
    "Genetic Algorithm",
    "Capacitor",
    "Self Repair",
    "Loop+1",
    "Go for the Eyes+1",
    "Hologram+1",
    "Recycle",
    "Biased Cognition",
    "Static Discharge+1"
  ],
  "special_seed": 0,
  "relics": [
    "Cracked Core",
    "Shuriken",
    "Prayer Wheel",
    "Blood Vial",
    "Bag of Preparation",
    "Pandora's Box",
    "MawBank",
    "Torii",
    "Red Mask",
    "Runic Pyramid",
    "Membership Card",
    "Anchor",
    "Sundial",
    "Dream Catcher",
    "OrangePellets",
    "Mummified Hand",
    "Boot",
    "Bottled Lightning"
  ],
  "potions_floor_usage": [
    56,
    56
  ],
  "damage_taken": [
    {
      "damage": 0,
      "enemies": "Small Slimes",
      "floor": 1,
      "turns": 3
    },
    {
      "damage": 3,
      "enemies": "2 Louse",
      "floor": 4,
      "turns": 3
    },
    {
      "damage": 35,
      "enemies": "3 Sentries",
      "floor": 7,
      "turns": 7
    },
    {
      "damage": 2,
      "enemies": "Jaw Worm",
      "floor": 8,
      "turns": 3
    },
    {
      "damage": 4,
      "enemies": "Blue Slaver",
      "floor": 12,
      "turns": 4
    },
    {
      "damage": 2,
      "enemies": "3 Louse",
      "floor": 14,
      "turns": 3
    },
    {
      "damage": 9,
      "enemies": "The Guardian",
      "floor": 16,
      "turns": 12
    },
    {
      "damage": 2,
      "enemies": "Spheric Guardian",
      "floor": 18,
      "turns": 4
    },
    {
      "damage": 1,
      "enemies": "3 Byrds",
      "floor": 21,
      "turns": 5
    },
    {
      "damage": 19,
      "enemies": "Shelled Parasite and Fungi",
      "floor": 22,
      "turns": 6
    },
    {
      "damage": 29,
      "enemies": "Slavers",
      "floor": 24,
      "turns": 6
    },
    {
      "damage": 14,
      "enemies": "Book of Stabbing",
      "floor": 27,
      "turns": 5
    },
    {
      "damage": 13,
      "enemies": "Masked Bandits",
      "floor": 28,
      "turns": 4
    },
    {
      "damage": 18,
      "enemies": "Snecko",
      "floor": 31,
      "turns": 4
    },
    {
      "damage": 0,
      "enemies": "Collector",
      "floor": 33,
      "turns": 7
    },
    {
      "damage": 10,
      "enemies": "3 Darklings",
      "floor": 35,
      "turns": 5
    },
    {
      "damage": 1,
      "enemies": "Nemesis",
      "floor": 41,
      "turns": 7
    },
    {
      "damage": 0,
      "enemies": "Giant Head",
      "floor": 44,
      "turns": 5
    },
    {
      "damage": 0,
      "enemies": "Orb Walker",
      "floor": 45,
      "turns": 4
    },
    {
      "damage": 0,
      "enemies": "Sphere and 2 Shapes",
      "floor": 46,
      "turns": 4
    },
    {
      "damage": 14,
      "enemies": "Awakened One",
      "floor": 50,
      "turns": 12
    },
    {
      "damage": 0,
      "enemies": "Time Eater",
      "floor": 51,
      "turns": 18
    },
    {
      "damage": 8,
      "enemies": "Shield and Spear",
      "floor": 55,
      "turns": 5
    },
    {
      "damage": 17,
      "enemies": "The Heart",
      "floor": 56,
      "turns": 8
    }
  ],
  "seed_played": "7839380660650326815",
  "potions_obtained": [
    {
      "floor": 1,
      "key": "SteroidPotion"
    },
    {
      "floor": 8,
      "key": "Block Potion"
    },
    {
      "floor": 12,
      "key": "Dexterity Potion"
    },
    {
      "floor": 18,
      "key": "Regen Potion"
    },
    {
      "floor": 24,
      "key": "SpeedPotion"
    },
    {
      "floor": 31,
      "key": "PowerPotion"
    },
    {
      "floor": 33,
      "key": "LiquidBronze"
    },
    {
      "floor": 41,
      "key": "Fire Potion"
    },
    {
      "floor": 45,
      "key": "FocusPotion"
    }
  ],
  "is_trial": false,
  "path_per_floor": [
    "M",
    "?",
    "?",
    "M",
    "T",
    "R",
    "E",
    "M",
    "T",
    "$",
    "R",
    "M",
    "R",
    "M",
    "R",
    "B",
    null,
    "M",
    "?",
    "?",
    "M",
    "M",
    "R",
    "E",
    "R",
    "T",
    "E",
    "?",
    "?",
    "R",
    "M",
    "R",
    "B",
    null,
    "M",
    "$",
    "?",
    "$",
    "?",
    "R",
    "E",
    "$",
    "T",
    "E",
    "M",
    "M",
    "R",
    "?",
    "R",
    "B",
    "B",
    null,
    "R",
    "$",
    "E",
    "B",
    null
  ],
  "character_chosen": "DEFECT",
  "items_purchased": [
    "Conserve Battery",
    "Regen Potion",
    "Membership Card",
    "Capacitor",
    "Anchor",
    "Sundial",
    "Self Repair",
    "OrangePellets",
    "Mummified Hand",
    "Biased Cognition"
  ],
  "campfire_rested": 3,
  "item_purchase_floors": [
    10,
    10,
    36,
    36,
    36,
    38,
    38,
    42,
    42,
    54
  ],
  "current_hp_per_floor": [
    71,
    60,
    34,
    31,
    31,
    54,
    19,
    19,
    19,
    19,
    19,
    29,
    29,
    29,
    29,
    22,
    64,
    64,
    64,
    64,
    65,
    63,
    63,
    36,
    59,
    59,
    47,
    36,
    36,
    36,
    20,
    43,
    45,
    70,
    62,
    62,
    62,
    62,
    62,
    62,
    70,
    70,
    70,
    74,
    74,
    74,
    74,
    74,
    74,
    67,
    74,
    74,
    74,
    74,
    74,
    64
  ],
  "gold": 60,
  "neow_bonus": "TEN_PERCENT_HP_BONUS",
  "is_prod": false,
  "is_daily": false,
  "chose_seed": false,
  "campfire_upgraded": 8,
  "win_rate": 0,
  "timestamp": 1551648868,
  "path_taken": [
    "M",
    "?",
    "?",
    "M",
    "?",
    "R",
    "E",
    "M",
    "T",
    "?",
    "R",
    "M",
    "R",
    "M",
    "R",
    "BOSS",
    "M",
    "?",
    "?",
    "M",
    "M",
    "R",
    "E",
    "R",
    "T",
    "E",
    "?",
    "?",
    "R",
    "M",
    "R",
    "BOSS",
    "M",
    "$",
    "?",
    "$",
    "?",
    "R",
    "E",
    "?",
    "T",
    "E",
    "?",
    "M",
    "R",
    "?",
    "R",
    "BOSS",
    "BOSS",
    "R",
    "$",
    "E",
    "BOSS"
  ],
  "build_version": "2019-02-06",
  "purchased_purges": 2,
  "victory": true,
  "max_hp_per_floor": [
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74,
    74
  ],
  "card_choices": [
    {
      "not_picked": [
        "Sunder",
        "Sweeping Beam"
      ],
      "picked": "Compile Driver",
      "floor": 1
    },
    {
      "not_picked": [
        "Heatsinks",
        "Steam",
        "Sunder"
      ],
      "picked": "SKIP",
      "floor": 4
    },
    {
      "not_picked": [
        "Heatsinks",
        "Streamline"
      ],
      "picked": "Gash",
      "floor": 7
    },
    {
      "not_picked": [
        "Double Energy",
        "Barrage"
      ],
      "picked": "Coolheaded",
      "floor": 8
    },
    {
      "not_picked": [
        "Turbo",
        "Force Field",
        "Scrape"
      ],
      "picked": "SKIP",
      "floor": 8
    },
    {
      "not_picked": [
        "White Noise",
        "Sunder"
      ],
      "picked": "Gash",
      "floor": 12
    },
    {
      "not_picked": [
        "Streamline",
        "Conserve Battery",
        "Amplify"
      ],
      "picked": "SKIP",
      "floor": 12
    },
    {
      "not_picked": [
        "Turbo",
        "Aggregate"
      ],
      "picked": "Fusion",
      "floor": 14
    },
    {
      "not_picked": [
        "Streamline",
        "Barrage"
      ],
      "picked": "Hologram",
      "floor": 14
    },
    {
      "not_picked": [
        "Thunder Strike",
        "Reboot"
      ],
      "picked": "Core Surge",
      "floor": 16
    },
    {
      "not_picked": [
        "Conserve Battery",
        "Sweeping Beam"
      ],
      "picked": "Steam+1",
      "floor": 18
    },
    {
      "not_picked": [
        "White Noise",
        "Consume",
        "Cold Snap"
      ],
      "picked": "SKIP",
      "floor": 18
    },
    {
      "not_picked": [
        "Redo",
        "Steam"
      ],
      "picked": "White Noise+1",
      "floor": 21
    },
    {
      "not_picked": [
        "Rainbow",
        "Rebound",
        "Heatsinks"
      ],
      "picked": "SKIP",
      "floor": 21
    },
    {
      "not_picked": [
        "Consume",
        "Streamline"
      ],
      "picked": "Coolheaded",
      "floor": 22
    },
    {
      "not_picked": [
        "Streamline",
        "Consume",
        "Fission"
      ],
      "picked": "SKIP",
      "floor": 22
    },
    {
      "not_picked": [
        "Genetic Algorithm",
        "Scrape"
      ],
      "picked": "Compile Driver",
      "floor": 24
    },
    {
      "not_picked": [
        "Conserve Battery",
        "Ball Lightning+1"
      ],
      "picked": "Biased Cognition",
      "floor": 27
    },
    {
      "not_picked": [
        "Turbo",
        "Leap"
      ],
      "picked": "Compile Driver",
      "floor": 28
    },
    {
      "not_picked": [
        "Ball Lightning",
        "Streamline",
        "Fusion"
      ],
      "picked": "SKIP",
      "floor": 31
    },
    {
      "not_picked": [
        "Force Field",
        "Leap",
        "Stack"
      ],
      "picked": "SKIP",
      "floor": 31
    },
    {
      "not_picked": [
        "Thunder Strike",
        "Amplify"
      ],
      "picked": "Fission",
      "floor": 33
    },
    {
      "not_picked": [
        "Compile Driver",
        "FTL"
      ],
      "picked": "Genetic Algorithm",
      "floor": 35
    },
    {
      "not_picked": [
        "Conserve Battery",
        "Steam Power",
        "Compile Driver+1"
      ],
      "picked": "SKIP",
      "floor": 35
    },
    {
      "not_picked": [
        "Lockon",
        "Double Energy",
        "Rainbow"
      ],
      "picked": "SKIP",
      "floor": 41
    },
    {
      "not_picked": [
        "Tempest",
        "Force Field+1"
      ],
      "picked": "Loop",
      "floor": 44
    },
    {
      "not_picked": [
        "Hologram",
        "Heatsinks"
      ],
      "picked": "Go for the Eyes+1",
      "floor": 45
    },
    {
      "not_picked": [
        "Compile Driver",
        "Cold Snap+1"
      ],
      "picked": "Hologram+1",
      "floor": 45
    },
    {
      "not_picked": [
        "Stack",
        "Turbo+1"
      ],
      "picked": "Recycle",
      "floor": 46
    },
    {
      "not_picked": [
        "Lockon+1",
        "Beam Cell",
        "Gash"
      ],
      "picked": "SKIP",
      "floor": 46
    },
    {
      "not_picked": [
        "Ball Lightning",
        "Chaos"
      ],
      "picked": "Static Discharge+1",
      "floor": 55
    }
  ],
  "player_experience": 5014514,
  "relics_obtained": [
    {
      "floor": 5,
      "key": "Prayer Wheel"
    },
    {
      "floor": 7,
      "key": "Blood Vial"
    },
    {
      "floor": 9,
      "key": "Bag of Preparation"
    },
    {
      "floor": 24,
      "key": "MawBank"
    },
    {
      "floor": 27,
      "key": "Torii"
    },
    {
      "floor": 28,
      "key": "Red Mask"
    },
    {
      "floor": 41,
      "key": "Dream Catcher"
    },
    {
      "floor": 43,
      "key": "Boot"
    },
    {
      "floor": 44,
      "key": "Bottled Lightning"
    }
  ],
  "event_choices": [
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 75,
      "event_name": "World of Goop",
      "player_choice": "Gather Gold",
      "floor": 2,
      "gold_loss": 0,
      "damage_taken": 11
    },
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "event_name": "Scrap Ooze",
      "player_choice": "Success",
      "floor": 3,
      "gold_loss": 0,
      "damage_taken": 26,
      "relics_obtained": [
        "Shuriken"
      ]
    },
    {
      "cards_removed": [
        "Chaos"
      ],
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "event_name": "Back to Basics",
      "player_choice": "Elegance",
      "floor": 19,
      "gold_loss": 0,
      "damage_taken": 0
    },
    {
      "cards_removed": [
        "Chaos"
      ],
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "event_name": "Beggar",
      "player_choice": "Gave Gold",
      "floor": 20,
      "gold_loss": 75,
      "damage_taken": 0
    },
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "event_name": "Masked Bandits",
      "player_choice": "Fought Bandits",
      "floor": 28,
      "gold_loss": 0,
      "damage_taken": 0
    },
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "cards_transformed": [
        "Auto Shields",
        "Dualcast"
      ],
      "event_name": "Drug Dealer",
      "player_choice": "Became Test Subject",
      "floor": 29,
      "gold_loss": 0,
      "damage_taken": 0,
      "cards_obtained": [
        "BootSequence",
        "Barrage"
      ]
    },
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 4,
      "gold_gain": 0,
      "event_name": "Winding Halls",
      "player_choice": "Max HP",
      "floor": 37,
      "gold_loss": 0,
      "damage_taken": 0
    },
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 222,
      "event_name": "Tomb of Lord Red Mask",
      "player_choice": "Wore Mask",
      "floor": 39,
      "gold_loss": 0,
      "damage_taken": 0
    },
    {
      "cards_removed": [
        "Gash"
      ],
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "event_name": "Falling",
      "player_choice": "Removed Attack",
      "floor": 48,
      "gold_loss": 0,
      "damage_taken": 0
    }
  ],
  "is_beta": true,
  "boss_relics": [
    {
      "not_picked": [
        "Empty Cage",
        "Velvet Choker"
      ],
      "picked": "Pandora's Box"
    },
    {
      "not_picked": [
        "Runic Dome",
        "White Beast Statue"
      ],
      "picked": "Runic Pyramid"
    }
  ],
  "items_purged_floors": [
    10,
    54
  ],
  "is_endless": false,
  "potions_floor_spawned": [
    1,
    8,
    12,
    18,
    24,
    31,
    33,
    41,
    45,
    55
  ],
  "ascension_level": 20
}
