{
  "gold_per_floor": [
    118,
    7,
    20,
    35,
    35,
    35,
    52,
    84,
    131,
    131,
    148,
    148,
    180,
    197,
    197,
    275,
    275,
    287,
    287,
    5,
    23,
    38,
    38,
    50,
    50,
    74,
    87,
    187,
    216,
    227,
    237,
    237,
    316,
    316,
    336,
    49,
    62,
    62,
    75,
    100,
    111,
    140,
    140,
    165,
    165,
    77,
    88,
    108,
    108,
    108,
    108,
    108,
    108,
    27,
    57,
    57
  ],
  "floor_reached": 57,
  "playtime": 7021,
  "items_purged": [
    "Strike_B",
    "Strike_B"
  ],
  "score": 2806,
  "play_id": "f3ad3ccb-111d-4928-982f-7b4d10680f76",
  "local_time": "20190306155642",
  "is_ascension_mode": true,
  "campfire_choices": [
    {
      "data": "Zap",
      "floor": 6,
      "key": "SMITH"
    },
    {
      "data": "Consume",
      "floor": 10,
      "key": "SMITH"
    },
    {
      "data": "Sweeping Beam",
      "floor": 12,
      "key": "SMITH"
    },
    {
      "floor": 15,
      "key": "REST"
    },
    {
      "data": "Coolheaded",
      "floor": 25,
      "key": "SMITH"
    },
    {
      "data": "Defragment",
      "floor": 32,
      "key": "SMITH"
    },
    {
      "floor": 45,
      "key": "RECALL"
    },
    {
      "data": "Loop",
      "floor": 49,
      "key": "SMITH"
    },
    {
      "data": "Defragment",
      "floor": 53,
      "key": "SMITH"
    }
  ],
  "neow_cost": "NONE",
  "seed_source_timestamp": 0,
  "circlet_count": 0,
  "master_deck": [
    "AscendersBane",
    "Strike_B+1",
    "Defend_B",
    "Defend_B",
    "Defend_B",
    "Defend_B+1",
    "Zap+1",
    "Dualcast+1",
    "Coolheaded+1",
    "Self Repair",
    "Consume+1",
    "Cold Snap",
    "Go for the Eyes",
    "Sweeping Beam+1",
    "Compile Driver",
    "FTL",
    "Ball Lightning",
    "Electrodynamics",
    "Steam+1",
    "Self Repair",
    "Leap+1",
    "Doom and Gloom",
    "Seek+1",
    "Chill+1",
    "Skim+1",
    "Defragment+1",
    "Creative AI",
    "Coolheaded+1",
    "Coolheaded+1",
    "Loop+1",
    "Hologram+1",
    "Hologram+1",
    "Gash",
    "Loop+1",
    "Defragment+1",
    "Coolheaded+1",
    "Static Discharge",
    "Coolheaded+1"
  ],
  "special_seed": 0,
  "relics": [
    "Cracked Core",
    "Blue Candle",
    "Whetstone",
    "Dream Catcher",
    "Velvet Choker",
    "Toxic Egg 2",
    "Emotion Chip",
    "Cables",
    "Bottled Lightning",
    "Sozu",
    "War Paint",
    "Shuriken",
    "Potion Belt",
    "Omamori",
    "Boot"
  ],
  "potions_floor_usage": [
    56,
    56
  ],
  "damage_taken": [
    {
      "damage": 4,
      "enemies": "Jaw Worm",
      "floor": 1,
      "turns": 4
    },
    {
      "damage": 4,
      "enemies": "Cultist",
      "floor": 3,
      "turns": 4
    },
    {
      "damage": 9,
      "enemies": "2 Louse",
      "floor": 4,
      "turns": 5
    },
    {
      "damage": 4,
      "enemies": "Large Slime",
      "floor": 7,
      "turns": 5
    },
    {
      "damage": 10,
      "enemies": "Lagavulin",
      "floor": 8,
      "turns": 7
    },
    {
      "damage": 13,
      "enemies": "Red Slaver",
      "floor": 11,
      "turns": 5
    },
    {
      "damage": 34,
      "enemies": "Gremlin Nob",
      "floor": 13,
      "turns": 5
    },
    {
      "damage": 1,
      "enemies": "Exordium Thugs",
      "floor": 14,
      "turns": 4
    },
    {
      "damage": 8,
      "enemies": "Slime Boss",
      "floor": 16,
      "turns": 6
    },
    {
      "damage": 17,
      "enemies": "Shell Parasite",
      "floor": 18,
      "turns": 5
    },
    {
      "damage": 0,
      "enemies": "3 Byrds",
      "floor": 21,
      "turns": 2
    },
    {
      "damage": 8,
      "enemies": "Centurion and Healer",
      "floor": 22,
      "turns": 7
    },
    {
      "damage": 17,
      "enemies": "Sentry and Sphere",
      "floor": 24,
      "turns": 4
    },
    {
      "damage": 10,
      "enemies": "Snecko",
      "floor": 27,
      "turns": 7
    },
    {
      "damage": 13,
      "enemies": "Colosseum Slavers",
      "floor": 28,
      "turns": 4
    },
    {
      "damage": 7,
      "enemies": "Colosseum Nobs",
      "floor": 28,
      "turns": 3
    },
    {
      "damage": 13,
      "enemies": "Slavers",
      "floor": 29,
      "turns": 4
    },
    {
      "damage": 18,
      "enemies": "Shelled Parasite and Fungi",
      "floor": 30,
      "turns": 4
    },
    {
      "damage": 0,
      "enemies": "Centurion and Healer",
      "floor": 31,
      "turns": 6
    },
    {
      "damage": 32,
      "enemies": "Champ",
      "floor": 33,
      "turns": 13
    },
    {
      "damage": 0,
      "enemies": "Orb Walker",
      "floor": 35,
      "turns": 3
    },
    {
      "damage": 0,
      "enemies": "3 Darklings",
      "floor": 37,
      "turns": 3
    },
    {
      "damage": 24,
      "enemies": "Maw",
      "floor": 39,
      "turns": 7
    },
    {
      "damage": 22,
      "enemies": "Giant Head",
      "floor": 40,
      "turns": 17
    },
    {
      "damage": 7,
      "enemies": "Writhing Mass",
      "floor": 41,
      "turns": 8
    },
    {
      "damage": 0,
      "enemies": "Nemesis",
      "floor": 42,
      "turns": 13
    },
    {
      "damage": 10,
      "enemies": "Giant Head",
      "floor": 44,
      "turns": 19
    },
    {
      "damage": 0,
      "enemies": "3 Darklings",
      "floor": 47,
      "turns": 3
    },
    {
      "damage": 10,
      "enemies": "Transient",
      "floor": 48,
      "turns": 6
    },
    {
      "damage": 31,
      "enemies": "Awakened One",
      "floor": 50,
      "turns": 27
    },
    {
      "damage": 15,
      "enemies": "Time Eater",
      "floor": 51,
      "turns": 24
    },
    {
      "damage": 20,
      "enemies": "Shield and Spear",
      "floor": 55,
      "turns": 9
    },
    {
      "damage": 68,
      "enemies": "The Heart",
      "floor": 56,
      "turns": 14
    }
  ],
  "seed_played": "8591107352139221514",
  "potions_obtained": [
    {
      "floor": 3,
      "key": "Fire Potion"
    },
    {
      "floor": 7,
      "key": "Explosive Potion"
    },
    {
      "floor": 18,
      "key": "Dexterity Potion"
    },
    {
      "floor": 30,
      "key": "Weak Potion"
    }
  ],
  "is_trial": false,
  "path_per_floor": [
    "M",
    "$",
    "M",
    "M",
    "?",
    "R",
    "M",
    "E",
    "T",
    "R",
    "M",
    "R",
    "E",
    "M",
    "R",
    "B",
    null,
    "M",
    "?",
    "$",
    "M",
    "M",
    "$",
    "M",
    "R",
    "T",
    "M",
    "?",
    "E",
    "M",
    "M",
    "R",
    "B",
    null,
    "M",
    "$",
    "M",
    "?",
    "M",
    "E",
    "M",
    "E",
    "T",
    "E",
    "R",
    "$",
    "M",
    "M",
    "R",
    "B",
    "B",
    null,
    "R",
    "$",
    "E",
    "B",
    null
  ],
  "character_chosen": "DEFECT",
  "items_purchased": [
    "Self Repair",
    "Toxic Egg 2",
    "Coolheaded+1",
    "Loop",
    "Hologram+1",
    "Defragment",
    "Static Discharge"
  ],
  "campfire_rested": 1,
  "item_purchase_floors": [
    2,
    20,
    36,
    36,
    36,
    46,
    54
  ],
  "current_hp_per_floor": [
    67,
    67,
    70,
    68,
    57,
    57,
    60,
    57,
    57,
    57,
    51,
    51,
    24,
    30,
    53,
    52,
    72,
    55,
    55,
    55,
    62,
    68,
    68,
    65,
    65,
    65,
    69,
    63,
    57,
    53,
    67,
    67,
    49,
    71,
    78,
    78,
    78,
    78,
    61,
    53,
    60,
    74,
    74,
    78,
    78,
    78,
    78,
    78,
    78,
    75,
    74,
    77,
    77,
    77,
    71,
    17
  ],
  "gold": 57,
  "neow_bonus": "TEN_PERCENT_HP_BONUS",
  "is_prod": false,
  "is_daily": false,
  "chose_seed": false,
  "campfire_upgraded": 7,
  "win_rate": 0,
  "timestamp": 1551916602,
  "path_taken": [
    "M",
    "$",
    "M",
    "M",
    "?",
    "R",
    "?",
    "E",
    "T",
    "R",
    "M",
    "R",
    "E",
    "M",
    "R",
    "BOSS",
    "M",
    "?",
    "$",
    "M",
    "M",
    "?",
    "M",
    "R",
    "T",
    "?",
    "?",
    "E",
    "M",
    "M",
    "R",
    "BOSS",
    "M",
    "$",
    "M",
    "?",
    "?",
    "E",
    "M",
    "E",
    "T",
    "E",
    "R",
    "?",
    "?",
    "M",
    "R",
    "BOSS",
    "BOSS",
    "R",
    "$",
    "E",
    "BOSS"
  ],
  "build_version": "2019-02-06",
  "purchased_purges": 2,
  "victory": true,
  "max_hp_per_floor": [
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78,
    78
  ],
  "card_choices": [
    {
      "not_picked": [
        "Go for the Eyes",
        "Leap"
      ],
      "picked": "Coolheaded",
      "floor": 1
    },
    {
      "not_picked": [
        "Coolheaded",
        "Steam"
      ],
      "picked": "Consume",
      "floor": 3
    },
    {
      "not_picked": [
        "Barrage",
        "Beam Cell"
      ],
      "picked": "Cold Snap",
      "floor": 4
    },
    {
      "not_picked": [
        "Streamline",
        "BootSequence"
      ],
      "picked": "Go for the Eyes",
      "floor": 7
    },
    {
      "not_picked": [
        "Rebound",
        "Steam",
        "Storm"
      ],
      "picked": "SKIP",
      "floor": 8
    },
    {
      "not_picked": [
        "Storm",
        "Melter"
      ],
      "picked": "Sweeping Beam",
      "floor": 11
    },
    {
      "not_picked": [
        "BootSequence",
        "Turbo"
      ],
      "picked": "Compile Driver",
      "floor": 13
    },
    {
      "not_picked": [
        "Streamline",
        "Force Field"
      ],
      "picked": "FTL",
      "floor": 14
    },
    {
      "not_picked": [
        "Hello World",
        "Gash"
      ],
      "picked": "Ball Lightning",
      "floor": 15
    },
    {
      "not_picked": [
        "Seek",
        "Multi-Cast"
      ],
      "picked": "Electrodynamics",
      "floor": 16
    },
    {
      "not_picked": [
        "Turbo",
        "White Noise+1"
      ],
      "picked": "Steam+1",
      "floor": 18
    },
    {
      "not_picked": [
        "Rebound",
        "Stack+1"
      ],
      "picked": "Leap+1",
      "floor": 21
    },
    {
      "not_picked": [
        "Redo+1",
        "Ball Lightning"
      ],
      "picked": "Doom and Gloom",
      "floor": 22
    },
    {
      "not_picked": [
        "Conserve Battery+1",
        "Rebound",
        "Ball Lightning"
      ],
      "picked": "SKIP",
      "floor": 24
    },
    {
      "not_picked": [
        "Compile Driver",
        "Beam Cell"
      ],
      "picked": "Seek+1",
      "floor": 27
    },
    {
      "not_picked": [
        "Aggregate+1",
        "Rebound"
      ],
      "picked": "Chill+1",
      "floor": 28
    },
    {
      "not_picked": [
        "Consume+1",
        "Storm+1"
      ],
      "picked": "Skim+1",
      "floor": 29
    },
    {
      "not_picked": [
        "Streamline",
        "Redo+1",
        "Go for the Eyes"
      ],
      "picked": "SKIP",
      "floor": 30
    },
    {
      "not_picked": [
        "Reinforced Body+1",
        "Biased Cognition"
      ],
      "picked": "Defragment",
      "floor": 31
    },
    {
      "not_picked": [
        "Electrodynamics",
        "Machine Learning"
      ],
      "picked": "Creative AI",
      "floor": 33
    },
    {
      "not_picked": [
        "Cold Snap",
        "Compile Driver"
      ],
      "picked": "Coolheaded+1",
      "floor": 35
    },
    {
      "not_picked": [
        "Rebound",
        "Barrage"
      ],
      "picked": "Hologram+1",
      "floor": 37
    },
    {
      "not_picked": [
        "Turbo+1",
        "Blizzard",
        "Gash"
      ],
      "picked": "SKIP",
      "floor": 39
    },
    {
      "not_picked": [
        "Steam+1",
        "Stack+1",
        "Go for the Eyes"
      ],
      "picked": "SKIP",
      "floor": 40
    },
    {
      "not_picked": [
        "Barrage",
        "Redo+1",
        "Leap+1"
      ],
      "picked": "SKIP",
      "floor": 41
    },
    {
      "not_picked": [
        "Barrage",
        "Redo+1",
        "Leap+1"
      ],
      "picked": "SKIP",
      "floor": 41
    },
    {
      "not_picked": [
        "Cold Snap",
        "Rebound",
        "Leap+1"
      ],
      "picked": "SKIP",
      "floor": 42
    },
    {
      "not_picked": [
        "Seek+1",
        "Rip and Tear"
      ],
      "picked": "Loop+1",
      "floor": 44
    },
    {
      "not_picked": [
        "Turbo+1",
        "Steam Power+1"
      ],
      "picked": "Coolheaded+1",
      "floor": 47
    },
    {
      "not_picked": [
        "White Noise+1",
        "Streamline+1",
        "Compile Driver+1"
      ],
      "picked": "SKIP",
      "floor": 48
    },
    {
      "not_picked": [
        "Undo+1",
        "Conserve Battery+1"
      ],
      "picked": "Coolheaded+1",
      "floor": 55
    }
  ],
  "player_experience": 5058529,
  "relics_obtained": [
    {
      "floor": 8,
      "key": "Blue Candle"
    },
    {
      "floor": 9,
      "key": "Whetstone"
    },
    {
      "floor": 13,
      "key": "Dream Catcher"
    },
    {
      "floor": 28,
      "key": "Emotion Chip"
    },
    {
      "floor": 28,
      "key": "Cables"
    },
    {
      "floor": 29,
      "key": "Bottled Lightning"
    },
    {
      "floor": 40,
      "key": "War Paint"
    },
    {
      "floor": 42,
      "key": "Shuriken"
    },
    {
      "floor": 43,
      "key": "Potion Belt"
    },
    {
      "floor": 44,
      "key": "Omamori"
    },
    {
      "floor": 55,
      "key": "Boot"
    }
  ],
  "event_choices": [
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "event_name": "Wheel of Change",
      "player_choice": "Damaged",
      "floor": 5,
      "gold_loss": 0,
      "damage_taken": 11
    },
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "event_name": "Match and Keep!",
      "player_choice": "1 cards matched",
      "floor": 19,
      "gold_loss": 0,
      "damage_taken": 0,
      "cards_obtained": [
        "Self Repair"
      ]
    },
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "event_name": "Colosseum",
      "player_choice": "Fight",
      "floor": 28,
      "gold_loss": 0,
      "damage_taken": 0
    },
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "event_name": "Colosseum",
      "player_choice": "Fought Nobs",
      "floor": 28,
      "gold_loss": 0,
      "damage_taken": 0
    },
    {
      "damage_healed": 0,
      "max_hp_gain": 0,
      "max_hp_loss": 0,
      "gold_gain": 0,
      "cards_transformed": [
        "Strike_B"
      ],
      "event_name": "Transmorgrifier",
      "player_choice": "Transformed",
      "floor": 38,
      "gold_loss": 0,
      "damage_taken": 0,
      "cards_obtained": [
        "Gash"
      ]
    }
  ],
  "is_beta": true,
  "boss_relics": [
    {
      "not_picked": [
        "Calling Bell",
        "Ectoplasm"
      ],
      "picked": "Velvet Choker"
    },
    {
      "not_picked": [
        "Pandora's Box",
        "Tiny House"
      ],
      "picked": "Sozu"
    }
  ],
  "items_purged_floors": [
    2,
    36
  ],
  "is_endless": false,
  "potions_floor_spawned": [
    3,
    7,
    18,
    24,
    28,
    30,
    37,
    39,
    47,
    55
  ],
  "ascension_level": 20
}
